// Builds the two vendored assets consumed by the extension's hep display path:
//
//   rust/assets/hep-viewer.js  — IIFE bundle of entry.js + hephaestus-svg-wasm
//   rust/assets/hep-assets.js  — sets globalThis.ggsqlHepAssets to the wasm
//                                binary and four Roboto faces, gzip+base64
//
// Re-run (`npm install && npm run build` in this directory) when bumping
// hephaestus-svg-wasm, and commit the regenerated assets. The npm package
// version must track the hephaestus crate the ggsql dependency links — the
// .hep document format version is compared for equality at load time.

import esbuild from "esbuild";
import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const assetsDir = path.resolve(moduleDir, "../../rust/assets");
// package.json is not in the package's "exports", so resolve the entry point
// and walk up to the package root.
const pkgDir = path.dirname(
  fileURLToPath(import.meta.resolve("hephaestus-svg-wasm")),
);

await esbuild.build({
  entryPoints: [path.join(moduleDir, "entry.js")],
  bundle: true,
  outfile: path.join(assetsDir, "hep-viewer.js"),
  format: "iife",
  // hephaestus-svg.js resolves its default wasm/font URLs against
  // import.meta.url at module scope; in an IIFE that is undefined and the URL
  // constructor throws while the bundle evaluates. Those defaults are never
  // used — entry.js passes wasm and font bytes explicitly — so any well-formed
  // base keeps module evaluation safe.
  define: { "import.meta.url": "document.baseURI" },
  target: ["es2020"],
  sourcemap: false,
  platform: "browser",
});

function asset(file) {
  return gzipSync(readFileSync(path.join(pkgDir, file)), { level: 9 }).toString(
    "base64",
  );
}

const faces = ["regular", "bold", "italic", "bolditalic"];
const fonts = faces
  .map((face) => `${face}: "${asset(`fonts/roboto-${face}.ttf`)}"`)
  .join(",\n    ");

const pkg = JSON.parse(
  readFileSync(path.join(pkgDir, "package.json"), "utf8"),
);

writeFileSync(
  path.join(assetsDir, "hep-assets.js"),
  `// AUTO-GENERATED by tools/hep-viewer/build.mjs from hephaestus-svg-wasm
// ${pkg.version} — do not edit. gzip+base64 of the wasm binary and the four
// bundled Roboto faces (OFL-1.1, see fonts/OFL-Roboto.txt in the npm package).
globalThis.ggsqlHepAssets = {
  version: "${pkg.version}",
  wasm: "${asset("hephaestus_svg_wasm_bg.wasm")}",
  fonts: {
    ${fonts}
  }
};
`,
);

console.log(`wrote hep-viewer.js and hep-assets.js (hephaestus-svg-wasm ${pkg.version})`);
